"""add assignee_id to tasks

Revision ID: 4bb3253e73a1
Revises: 
Create Date: 2026-05-01 14:51:32.274408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb3253e73a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tasks_assigned_to_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'])
    op.drop_column('tasks', 'assigned_to_id')
        # drop default first
    op.alter_column('users', 'role', server_default=None)

    # change type with cast
    op.alter_column(
        'users', 'role',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('admin', 'member', name='userrole'),
        existing_nullable=False,
        postgresql_using="role::userrole"
    )

    # set new default on enum
    op.alter_column(
        'users', 'role',
        server_default=sa.text("'member'::userrole")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'member', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"),
               postgresql_using="role::userrole")
    op.add_column('tasks', sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_to_id_fkey'), 'tasks', 'users', ['assigned_to_id'], ['id'])
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###
